### ISSUE TITLE
Add Pictures 

### ISSUE THREAD

**Issue by GamingTurtle** [GamingTurtle/ArduDuck#5]
Add Pictures to robert and ferdia's info

**Comment by RobertABT** [comment]
Will my Facebook profile pic do?

**Comment by GamingTurtle** [comment]
Yes just make sure it's the same resolution as /ApachePage/MarleyIcon.ext then upload it as /ApachePage/RobertIcon.ext

**Comment by GamingTurtle** [comment]
Robert Picture added!
